version: '3.8'

services:
  frontend:
    build: .
    container_name: infinity-frontend
    restart: always
    environment:
      - NODE_ENV=production
      - TRUST_PROXY=true
    ports:
      - "3000:3000"

  nginx:
    image: nginx:stable
    container_name: infinity-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443" # добавили HTTPS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certbot/conf:/etc/letsencrypt     # сертификаты
      - ./nginx/certbot/www:/var/www/certbot      # верификация
    depends_on:
      - frontend