version: '3.8'

services:
  frontend:
    build: .
    container_name: infinity-frontend
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  nginx:
    image: nginx:stable
    container_name: infinity-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend